feat(UserNavDropdown): introduce dropdown menu for userProfile nav
melfish-lorem/1tds pull request #102
Opened 2021-03-18 15:54 UTC by Nov66

- 新增 UserProfile 页面下的 dropdown menu
- rename 下拉菜单组件

2021-03-18 23:17 UTC, KieraDOG requested changes

2021-03-18 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +              top="56px"
这里需要 top 吗？

2021-03-18 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/components/ResponsiveBurgerMenu/ResponsiveBurgerMenu.jsx
> +            <Link variant="primary" href="/become-a-captain">
顺手把所有的 link 都改成普通颜色吧，给 link 一个 text variant，然后颜色就是 inheriant

2021-03-18 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +                <Button variant="naked" size="sm">登出</Button>
建一张卡做登出

2021-03-18 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +          <Icon name="userCircle" size="2x" onClick={handleClick} />
这个 Icon 要放在 Button 里面？

2021-03-18 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +        <>
这里面 Button + Menu 抽成一个 component？单一职责

2021-03-19 02:06 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +              top="56px"
如果没有 top 它就是飞在上面去了 可能是我设计有问题 我去看看 position 的问题

2021-03-19 02:07 UTC, Nov66 commented on src/app/Header/components/MenuLeft/components/ResponsiveBurgerMenu/ResponsiveBurgerMenu.jsx
> +            <Link variant="primary" href="/become-a-captain">
好！

2021-03-19 02:07 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +                <Button variant="naked" size="sm">登出</Button>
好的 建了！

2021-03-19 02:07 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +        <>
对对对对！！马上改！

2021-03-19 02:07 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +          <Icon name="userCircle" size="2x" onClick={handleClick} />
我的错 忽略了！！

2021-03-19 03:22 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +        <>
都改好了龙哥

2021-03-19 13:17 UTC, KieraDOG approved these changes

2021-03-19 13:17 UTC, merged