feat(LandingPage responsive): add responsive in landingPage
melfish-lorem/1tds pull request #113
Opened 2021-03-20 12:04 UTC by KarlokCheung

Achieve:

Apply styled-system in landing page and add responsive.

2021-03-20 23:52 UTC, KieraDOG requested changes

2021-03-20 23:52 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    <Box ml={[0, 0, 'lg']} my={['lg', 'lg', 0]}>
```suggestion
    <Box ml={[null, null, 'lg']} my={['lg', 'lg', 0]}>
```

2021-03-20 23:52 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +  <Flex py="lg">
这个 flex 不需要吧

2021-03-21 02:38 UTC, KarlokCheung commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    <Box ml={[0, 0, 'lg']} my={['lg', 'lg', 0]}>
马上改，马上改

2021-03-21 02:40 UTC, KarlokCheung commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +  <Flex py="lg">
是的，不需要，这里有点偷懒照着改了当时欠考虑， 马上改成box

2021-03-21 02:47 UTC, KarlokCheung commented
已改好

2021-03-21 03:06 UTC, Jakeeeeeeeee commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +  <Flex flexWrap={['wrap', null, 'initial']} mt={['1x', null, 0]} py="sm">
这一行有点长，可以换个行

2021-03-21 03:06 UTC, Jakeeeeeeeee commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    <Box width="100%" bg="grey" borderRadius="default">
Box 默认宽度好像是100%？应该不需要width="100%"

2021-03-21 03:13 UTC, KarlokCheung commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    <Box width="100%" bg="grey" borderRadius="default">
哦哦这个不太行，拿掉width的话这个box的宽度会掉到input size一样，在这里会缩小

2021-03-21 03:15 UTC, KarlokCheung commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +  <Flex flexWrap={['wrap', null, 'initial']} mt={['1x', null, 0]} py="sm">
嗯嗯好的， 改好了之后看起来顺眼了一些

2021-03-21 03:17 UTC, KarlokCheung commented
SearchBar 内Flex的props换行， 已改好

2021-03-21 08:19 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    <Box width="100%" bg="grey" borderRadius="default">
> Box 默认宽度好像是100%？应该不需要width="100%"

他是因为 flex 里面

2021-03-21 08:19 UTC, KieraDOG requested changes

2021-03-21 08:19 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +      my={['lg', 'lg', 0]}
```suggestion
      my={['lg', null, 0]}
```

2021-03-21 09:49 UTC, KarlokCheung commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +      my={['lg', 'lg', 0]}
已改好

2021-03-21 23:26 UTC, KieraDOG commented on src/app/LandingPage/LandingPage.jsx
> +      <Box px={['md', 'lg', '3x']} mt={['2x', null, '3x']}>
```suggestion
      <Box px={['md', null, '3x']} mt={['2x', null, '3x']}>
```

2021-03-21 23:26 UTC, KieraDOG approved these changes

2021-03-21 23:27 UTC, merged