feat(reset-password): add reset password function to profile page
melfish-lorem/1tds pull request #119
Opened 2021-03-22 13:33 UTC by SimonYu-Web

按钮现在可以修改密码了
顺手改了theme

2021-03-22 14:03 UTC, SimonYu-Web commented
这个跟Jessie做的有conflict  等jessie的merge进去之后我就可以解决

2021-03-22 14:03 UTC, KieraDOG requested changes

2021-03-22 14:03 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +          忘记密码？
在 user profile 页面 忘记密码？那用户是怎么登录进来的？

2021-03-23 10:20 UTC, SimonYu-Web commented
这次搞定了

2021-03-23 12:51 UTC, SimonYu-Web commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +import React, { useState } from 'react';
目前实现的修改密码弹窗以及input的要求
这个文件有一些内容
需要在后端做好之后再做修改
主要是根据httpRequestStatus的反应
请龙哥忽略一下...

2021-03-23 12:55 UTC, SimonYu-Web commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +            }[httpRequestStatus]}
这里的内容需要在后端做好之后再做修改
主要是根据httpRequestStatus的反馈
请龙哥忽略一下...

2021-03-23 13:27 UTC, KieraDOG requested changes

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +        setHttpRequestStatus(status);
重置密码成功直接关掉当前modal就可以了
建一张卡去显示 global message

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +                  <Button variant="naked" onClick={() => setModal(MODAL.USER_AUTH_MODAL)}>点击重新登录</Button>
用户是修改密码 修改密码！！！ 他登录进来自己修改密码 为什么要重新登录呀

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +          <ForgetPasswordModal
这里为什么会有 forget password 用户都已经登录进来了

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +        [MODAL.USER_AUTH_MODAL]: (
同理

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/formConfig.js
> +    getErrorMessage: (confirmPassword, formValues) => getMessage([
strong password？

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +    <Modal title={title} onClose={onClose} size="sm">
这个改动？不需要吧

2021-03-23 13:27 UTC, KieraDOG commented on src/app/LoginModal/LoginModal.jsx
> +  // const [forgetPassword, setForgetPassword] = useState(false);
？？？

2021-03-23 13:27 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> -    <Box px="sm">
这里需要改 layout 吗？ 你是实现点击button 出弹窗，本来的样式不需要做改动吧

2021-03-23 13:27 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +  const { token } = router.query;
修改密码不需要 token 吧？

2021-03-24 01:22 UTC, SimonYu-Web commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +        setHttpRequestStatus(status);
新PR还是draft   这个部分有点没懂  还需要再改

2021-03-24 01:24 UTC, SimonYu-Web commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +    <Modal title={title} onClose={onClose} size="sm">
需要  这里影响了弹窗的标题显示   其他文件中都做了改变  现在忘记密码和修改密码都可以正常显示了

2021-03-24 01:28 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +    <Modal title={title} onClose={onClose} size="sm">
我的意思是 这个是 ForgetPasswordModal，不应该出现其他 title 呀

2021-03-24 13:42 UTC, SimonYu-Web commented
已完成：修改密码纯静态部分
1.changePassword的弹窗
2.input的限制
未完成：

修改密码的api集成（已建卡）
修改密码后端

如果静态部分没问题可以先merge进master

2021-03-24 13:55 UTC, KieraDOG requested changes

2021-03-24 13:55 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +  } = useApi(resetPassword, { onSuccess });
这应该是一个新的 API？ 比如 changePassword？

2021-03-24 13:55 UTC, KieraDOG commented on src/app/ChangePasswordModal/formConfig.js
> +        error: !validator.isStrongPassword(confirmPassword, { minUppercase: 0, minSymbols: 0 }),
confirm 就不需要再提示复杂密码了

2021-03-24 13:55 UTC, KieraDOG commented on src/app/UserAuthModals/UserAuthModals.jsx
> +        title="忘记密码?"
这里不需要？

2021-03-24 13:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +          <Button size="sm" type="submit" variant="primary" onClick={() => setChangePassword(true)}>
modal 放在最外面？

2021-03-24 13:58 UTC, KieraDOG commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +  } = useApi(resetPassword, { onSuccess });
这里另外一张卡做的话就 onSubmit 直接 console log 吧

2021-03-24 14:00 UTC, SimonYu-Web commented on src/app/ChangePasswordModal/ChangePasswordModal.jsx
> +  } = useApi(resetPassword, { onSuccess });
对  这个是张新卡   那我先把这部分删掉吧  等做好之后再用

2021-03-24 14:00 UTC, SimonYu-Web commented on src/app/ChangePasswordModal/formConfig.js
> +        error: !validator.isStrongPassword(confirmPassword, { minUppercase: 0, minSymbols: 0 }),
![image](https://user-images.githubusercontent.com/31500670/112322975-77407d00-8d05-11eb-934b-5d5c1854e18e.png)
这个本来是没有的   那可能龙哥之前看错了

2021-03-24 15:18 UTC, KieraDOG requested changes

2021-03-24 15:18 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +      {changePassword && <ChangePasswordModal onClose={() => setChangePassword(false)} />}
最外面放一个 fragement

2021-03-24 15:21 UTC, KieraDOG approved these changes

2021-03-24 15:23 UTC, merged