Simon/recruitment marketing page
melfish-lorem/1tds pull request #18
Opened 2021-02-23 05:10 UTC by SimonYu-Web

Archieve:
团长招募静态marketing部分

未完工作：
1.等designer完善后更新内容
2.responsive

2021-02-23 05:11 UTC, SimonYu-Web commented
预览页面用 /marketing

2021-02-23 05:25 UTC, JavaScriptN0ob requested changes

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/Benefits/Benefits.jsx
> +const data = [
@KieraDOG 龙哥，这里的data要做一个constant.js提出来吗?
不知道后续会不会更新页面上的内容

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/Benefits/Benefits.jsx
> +              <img src={icon} alt={iconAlt} width="72px" />
Next.js是不是得用next/image 的 ```<Image>```来展示图片

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/BusinessProcess/BusinessProcess.jsx
> +  margin: auto;
发现一个空行

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +font-style: normal;
缩进格式问题，prelint是不是没工作啊

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/ShareExperience/ShareExperience.jsx
> +height: 98px;
这里也有

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/ShareExperience/ShareExperience.jsx
> +const UserImage = styled.div``;
这个空的SC是啥

2021-02-23 05:25 UTC, JavaScriptN0ob commented on src/app/MarketingPage/components/ShareExperience/ShareExperience.jsx
> +
Description可否做成p-tag @KieraDOG

2021-02-23 05:59 UTC, KieraDOG commented on src/app/MarketingPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +font-style: normal;
eslint 是针对 js 的 所以 css 检查不出来

2021-02-23 06:00 UTC, KieraDOG commented on src/app/MarketingPage/components/Benefits/Benefits.jsx
> +const data = [
目前先不用，没有复用性

2021-02-23 13:16 UTC, SimonYu-Web commented
已完成：
上面两个部分完善了布局
根据UI目前的进度补充了下两个的内容

还需要做：
页面跳转
第三个版块的切换
补充第四版块内容

2021-02-23 13:43 UTC, KieraDOG requested changes
我先 review 这些，我发现你很多 css 是直接从 figma 上抄下来的，这是不对的，你要有分析哪些是你需要的，哪些是 figma 生成的无用的

改好之后我再继续看吧

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/BecomeACaptainPage.jsx
> +        <ShareExperience />
这一个 section 删掉吧，我一时半会应该找不到相关的文案

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  line-height: 26px;
line-height 用倍数
```suggestion
  line-height: 1.75;
```

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  line-height: 32px;
这个单行文字不需要 line-height

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  font-family: Manrope;
font-family 用已经有的那个 "ZCOOL KuaiLe";

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  width: 1110px;
width 这里用我写好的 Container 组件

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  margin-left: 165px;
居中应该用 margin: 0 auto;

不过你直接用我写好的 Container 就没这个问题了

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  margin-top: 96px;
这个 gap 有点太大了，相应的调小点吧

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  font-feature-settings: 'liga' off;
不要直接从 figma 上抄 css 下来，这里需要自己检讨下

2021-02-23 13:43 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  margin-left: 165px;
居中应该用 margin: 0 auto;

不过你直接用我写好的 Container 就没这个问题了

2021-02-24 05:34 UTC, KieraDOG commented on src/app/BecomeACaptainPage/BecomeACaptainPage.jsx
> +const MarketingContainer = styled.div`
这个不是讲过不需要了？

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +
?????

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  height: 600px;
不要用 height 和 width 去控制， 用 padding 或者 margin

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  height: 400px;
同上

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  height: 232px;
近5凑整

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  padding: 5px 10px;
用 4 的倍数

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  margin:20px 0;
空格

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  border-bottom: 112px;
border-bottom ？

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  margin-top: 10px;
4的倍数

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +  font-family: Manrope;
用普通 font

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  width: 1000px;
同上

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  margin: 0 auto;
text-align center 应该就够吧？

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  padding: 0px;
默认就是 0？

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  font-family: Microsoft YaHei;
默认就是 yahei

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  font-size: 16px;
默认 font-size 就是 16

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  letter-spacing: 1px;
这个需要吗？

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +  margin-top: 15px;
4的倍数

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +  width: 1000px;
同上

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +  height: 500px;
同上

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +  width: 850px;
同上

2021-02-24 05:41 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/ShareExperience/ShareExperience.jsx
> +import React from 'react';
这个文件可以删了？

2021-02-24 09:01 UTC, KieraDOG approved these changes

2021-02-25 00:47 UTC, Nov66 commented on src/app/BecomeACaptainPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +      </Link>
这里的 BecomeCaptainButton 是不是应该还是跳转到成为团长页 而不是 landing page？

2021-02-25 00:52 UTC, Nov66 commented on src/app/BecomeACaptainPage/BecomeACaptainPage.jsx.orig
> +import React from 'react';
这整个文件是干啥的哦 是解决了conflict 忘记删了吗

2021-02-25 00:54 UTC, SimonYu-Web commented on src/app/BecomeACaptainPage/components/CaptainLinkBlock/CaptainLinkBlock.jsx
> +      </Link>
好问题  我改一下

2021-02-25 00:54 UTC, SimonYu-Web commented on src/app/BecomeACaptainPage/BecomeACaptainPage.jsx.orig
> +import React from 'react';
对  应该删掉的

2021-02-25 01:30 UTC, Jakeeeeeeeee commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +              <Image alt={iconAlt} src={icon} width={100} height={100} />
alt里的props命名是否可以是{key},  然后把复用的key改成相应的值

2021-02-25 01:39 UTC, Jakeeeeeeeee approved these changes

2021-02-25 01:39 UTC, Jakeeeeeeeee commented on src/app/BecomeACaptainPage/components/Benefits/Benefits.jsx
> +    iconAlt: '运营支持',
iconAlt里的内容可以写在key 里

2021-02-25 05:08 UTC, JavaScriptN0ob requested changes
so far so good，把俩问题改一下：
1. `Benefits.jsx` 里 css重复问题修一下。
2.  `BusinessProcess.jsx` 里静态数据key和alt的问题参考之前`Benefits.jsx`修改一下

2021-02-25 05:08 UTC, JavaScriptN0ob commented on src/app/BecomeACaptainPage/components/BusinessProcess/BusinessProcess.jsx
> +    key: '1',
这里的key和alt是不是也可以像前面Benifits.jsx那样改，alt用中文吧

2021-02-25 05:14 UTC, JavaScriptN0ob commented
还有一个问题： pr增加了10个图片类资源，但是后面文件里只用了8个，看看是不是把没用的资源删掉。

还有public/icons和background我觉得命名很好，但是photos命名一般，看看怎么重新起个名字

2021-02-25 12:41 UTC, Jakeeeeeeeee submitted a review, later dismissed

2021-02-25 12:44 UTC, JavaScriptN0ob approved these changes
LGTM

2021-02-25 12:50 UTC, hachilam92 approved these changes
data部分用title作为key有点奇怪，其他看起来没什么问题

2021-02-25 12:51 UTC, merged