Jessie/landingpage
melfish-lorem/1tds pull request #20
Opened 2021-02-23 11:30 UTC by jessieease

1 add LandingPage components with Slogan and SearchBar
2 fix searchBar outline 
3 add the placeholder responsive with user clicks

2021-02-23 13:28 UTC, KieraDOG commented
从用户体验的角度上来讲有几个问题，
1. input placeholder 的字体大小和我输入的字体大小不一致
2. 查找团购这个 Button 感官上大小和 Input 不配套
3. input 左面 place icon 的 margin-left 和 右面 search 的 margin-right 是不是不一致？

2021-02-24 04:25 UTC, jessieease commented
- 增加了‘xl’ 的button， 应用在主页Button
- 修改了input字符大小与placeholder大小不一致问题
- 调整了searchBar大小和Button大小不协调问题

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +`;
缩进？

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/LandingPage.jsx
> +    display:flex;
定高，然后水平居底部，再加一些 margin-bottom，比子组件  margin-top 好

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    }
去掉 placeholder

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    width: 603px;
取整数？

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    margin: 0px 109px;
margin-left 小一点是不是好看一些？

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    position: static;
这个不需要吧？

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    border-radius: 25px;
border-radius 小一些，就和 button 的 br 一致吧

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +        }}
placeholder 去掉吧

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +          src="/images/icons/searchIcon2.svg"
这里为什么是 searchIcon2？

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +  const [placeHolder, setPlaceHolder] = useState('输入地址：xxx');
去掉 placeholder

2021-02-24 04:39 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +      <h1>Welcome to 一团袋鼠🦘</h1>
看看附近在团些什么好东西吧! 字体用 ZCOOL 那个

2021-02-24 04:39 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    `,
👍

2021-02-24 11:33 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +`;
是的，InputWapper里先放placeIcon再放Input框

2021-02-24 11:34 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    }
已改

2021-02-24 11:34 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    width: 603px;
已改

2021-02-24 11:34 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +    margin: 0px 109px;
已改为72px; 确实好看了非常多👍

2021-02-24 11:34 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +        }}
已去

2021-02-24 11:35 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +          src="/images/icons/searchIcon2.svg"
因为和导航栏的SearchIcon颜色不一样，这里需要调整吗

2021-02-24 11:35 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +  const [placeHolder, setPlaceHolder] = useState('输入地址：xxx');
已改

2021-02-24 11:36 UTC, jessieease commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +      <h1>Welcome to 一团袋鼠🦘</h1>
已换并调整了字体大小结构

2021-02-24 12:23 UTC, jessieease commented on src/app/LandingPage/LandingPage.jsx
> +    display:flex;
已改

2021-02-24 22:58 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +          src="/images/icons/searchIcon2.svg"
svg 应该可以通过 css 换颜色的，你查一下

2021-02-24 22:58 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +          src="/images/icons/searchIcon2.svg"
如果不可以，那也应该起个 meaningful 的名字，比如 primaryColorSearchIcon.svg，但是我推荐用 css 改颜色

2021-02-24 23:05 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +      <h1>Welcome to 一团袋鼠🦘</h1>
font-weight 调到300吧

2021-02-24 23:07 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-feature-settings: 'liga' off;
这个是不是从 figma 上抄下来的？不需要
```suggestion
    letter-spacing: 8px;
```

2021-02-24 23:09 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +const Heading = styled.div`
给个 font-weight: 300 吧，现在有点太大了

2021-02-24 23:09 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    width: 722px;
这个我在别的 PR 里面强调过多次了，不要用 position 或者 margin-left + width 来居中

居中因该用 width + margin: auto

我做了一个公用的 `<Container />` 组件，你直接调用做居中

2021-02-24 23:09 UTC, KieraDOG commented on src/app/LandingPage/LandingPage.jsx
> +    position:relative;
这里冒号后面空一格？

2021-02-25 01:29 UTC, jessieease commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-feature-settings: 'liga' off;
已改

2021-02-25 01:31 UTC, jessieease commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +const Heading = styled.div`
已改，现在大小适中

2021-02-25 01:41 UTC, jessieease commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    width: 722px;
收到 已改

2021-02-25 02:09 UTC, Jakeeeeeeeee approved these changes

2021-02-25 05:19 UTC, JavaScriptN0ob requested changes
解决是否复用`Input.jsx`和`font-weight`问题就ok啦

2021-02-25 05:19 UTC, JavaScriptN0ob commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +const Input = styled.input`
这个Input可以复用component里面那个吗？

2021-02-25 05:19 UTC, JavaScriptN0ob commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +        alt="Location"
这里我想询问一下 @KieraDOG 我们的目标客户是华人，那alt是在图片没正常加载的时候显示 | disable accessability的用法，是不是alt用中文？

2021-02-25 05:19 UTC, JavaScriptN0ob commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-weight: 300px;
font-weight是没有px的，https://www.w3schools.com/cssref/pr_font_weight.asp

2021-02-25 05:27 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +        alt="Location"
嗯 alt 用中文 ok 的

2021-02-25 05:27 UTC, KieraDOG commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +const Input = styled.input`
Input 的 suffix 和 prefix 还没做好

2021-02-25 05:31 UTC, jessieease commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-weight: 300px;
已改，感恩提醒👍

2021-02-25 05:32 UTC, jessieease commented on src/app/LandingPage/components/SearchBar/SearchBar.jsx
> +        alt="Location"
已改为中文

2021-02-25 05:46 UTC, KieraDOG commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-weight: 300px;
感恩有点太严重了 😂 哈哈哈

2021-02-25 09:50 UTC, JavaScriptN0ob commented on src/app/LandingPage/components/Slogan/Slogan.jsx
> +    font-weight: 300px;
:speak_no_evil:

2021-02-25 22:54 UTC, KieraDOG approved these changes

2021-02-25 22:57 UTC, merged