Feature: Karlok
melfish-lorem/1tds pull request #23
Opened 2021-02-25 04:56 UTC by KarlokCheung

Achieve: 
1: Add Input with preset size: sm default lg el...
2. Add Input Container with optional prefix & suffix
3. Add Input Group with optional attributes(includes error messages & Label)
4. Apply changes to form & search bar with reusable InputGroup component.

2021-02-25 05:30 UTC, KieraDOG commented
好多地方都出错了 
![image](https://user-images.githubusercontent.com/6457082/109107892-a7d4db80-7786-11eb-9635-d8c9d03e8486.png)
![image](https://user-images.githubusercontent.com/6457082/109107924-b1f6da00-7786-11eb-8808-baa659aed8c6.png)

2021-02-25 05:33 UTC, JavaScriptN0ob approved these changes
把SC里面选择器改掉，我觉得就ok了

2021-02-25 05:33 UTC, JavaScriptN0ob commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +              label={config[key].label}
:thumbsup:

2021-02-25 05:33 UTC, JavaScriptN0ob commented on src/components/InputContainer/InputContainer.jsx
> +  & input {
这里要拆出来，SC里面不要出现除了pseudo伪类之外的选择器，这给SC写成scss了

2021-02-25 06:31 UTC, KarlokCheung commented
> 好多地方都出错了
> ![image](https://user-images.githubusercontent.com/6457082/109107892-a7d4db80-7786-11eb-9635-d8c9d03e8486.png)
> ![image](https://user-images.githubusercontent.com/6457082/109107924-b1f6da00-7786-11eb-8808-baa659aed8c6.png)

这里应该是我刚才忘了吧原来的Input改成新的InputGroup, 现在已经改了，龙哥看看现在好了吗？

2021-02-26 05:33 UTC, KarlokCheung commented
> > 好多地方都出错了
> > ![image](https://user-images.githubusercontent.com/6457082/109107892-a7d4db80-7786-11eb-9635-d8c9d03e8486.png)
> > ![image](https://user-images.githubusercontent.com/6457082/109107924-b1f6da00-7786-11eb-8808-baa659aed8c6.png)
> 
> 这里应该是我刚才忘了吧原来的Input改成新的InputGroup, 现在已经改了，龙哥看看现在好了吗？


现在已经全部改好了，还顺手把首页的xl 搜索和input，还有修正了form和login里面的尺寸错误。

2021-02-28 09:35 UTC, KarlokCheung commented
Fix: 
1. 解决了Header内Search bar跟登陆Button不同高
2. 取消了Landing Page内的Search bar的letter-spacing

2021-02-28 23:16 UTC, KieraDOG requested changes
这个 PR 和 Jake 的 FormItem 已经冲突太多了，我觉着可以重新做这部分内容了

2021-02-28 23:16 UTC, KieraDOG commented on src/components/InputTextField/InputTextField.jsx
> +      width: 176px;
input 不应该定宽，考虑复用性的话，定宽的 input 没有任何 reusable 可言

2021-02-28 23:16 UTC, KieraDOG commented on src/components/InputTextField/InputTextField.jsx
> +const InputTextField = styled.input`
这个直接叫 Input 就好

```suggestion
const Input = styled.input`
```

2021-02-28 23:16 UTC, KieraDOG commented on src/components/InputContainer/InputContainer.jsx
> +import styled, { css } from 'styled-components';
这个组件的意义是？

2021-03-01 12:34 UTC, closed without merging