Jake/form item
melfish-lorem/1tds pull request #25
Opened 2021-02-25 17:29 UTC by Jakeeeeeeeee

achieved:

1. FormItem复用组件:
  1) wrap layout
  2) inline layout
  3) label
  4)input
  5)error message

2.Login modal 复用 FormItem

3.成为团长页面复用 FormItem

2021-02-25 21:58 UTC, JavaScriptN0ob requested changes

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +            layout="inline"
如果layout表示的是 label与input的关系，我觉得可以改名叫labelLayout更加readable

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +  font-family: "ZCOOL KuaiLe";
这里single quote与double quote，取决于整个代码的引号习惯，要做到一致
查看了项目中其他SC，都是single quote，这里需要修改。

文档： https://eslint.org/docs/rules/quote-props#consistent-as-needed

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
>    margin: 0px 200px 52px 200px;
这里左右 200px 要不要做个缩写
``` margin: 0px 200px 52px;```

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
>    margin: 50px auto 28px auto;
同上

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +              const errorMessage = config[key].getErrorMessage?.(
这里是prettier自动修改的吗，我觉得换行看起来怪怪的。这里 @KieraDOG 来答疑一下

2021-02-25 21:58 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +                  layout="block"
同前面layout

2021-02-25 22:58 UTC, KieraDOG commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +              const errorMessage = config[key].getErrorMessage?.(
之前的写法好一些

2021-02-25 22:59 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +            layout="inline"
layout 代表 FormItem 的排列方式，这个 prop 问题不大

2021-02-26 00:59 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +      <Input
Input 作为 children 传进来比较好，方便以后做复用，比如 FormItem + Select，或者 FormItem + Textarea

2021-02-26 00:59 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +  <Wrapper layout={layout}>
做两个 Flex 吧，这样能实现各种不同情况下的 label 居中
```
<>
  <Layout>
    <LabelWrapper>{label}</LabelWrapper>
    <div>{children}</div>
  </Layout>
  {errorMessage && (
    <Layout>
      <LabelWrapper />
      <ErrorMessage />
    </Layout>
  )}
<>
```

2021-02-26 05:44 UTC, closed without merging