Formitem
melfish-lorem/1tds pull request #34
Opened 2021-02-26 17:37 UTC by Jakeeeeeeeee

Achieved:
1. FormItem 复用组件 - layout, label, errormessage
2. Login 复用 formitem
3. become a caption Page 复用 formitem
4. contactContent 复用formitem

2021-02-27 01:32 UTC, hachilam92 reviewed
不应该有package-lock.json吧，是用了npm吗

2021-02-27 01:47 UTC, hachilam92 commented on src/components/FormItem/FormItem.jsx
> +  <Form>
Form改成container或者FormItemWrapper之类的可能比较好，FormItem里面包着Form看上去会有点奇怪

2021-02-27 01:47 UTC, hachilam92 commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +              <LargeInput
这里感觉FormItem的样式设置被拆成了两部分，一部分需要通过layout attribute控制，另一部分需要通过child component 传入自定义样式的input，感觉复用起来有点绕；

有没有可能把input整合进FormItem然后同样通过attribute来控制样式呢

2021-02-27 11:36 UTC, Jakeeeeeeeee commented
> 不应该有package-lock.json吧，是用了npm吗

对用了Npm install uuid,

2021-02-27 13:42 UTC, JavaScriptN0ob commented
npm与yarn不可以同时用

Jakeeeeeeeee <notifications@github.com>于2021年2月27日 周六22:36写道：

> 不应该有package-lock.json吧，是用了npm吗
>
> 对用了Npm install uuid,
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/melfish-lorem/1tds/pull/34#issuecomment-787059394>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEIKGFKQBNITBCL6D3ZZ43TBDKLTANCNFSM4YI2TCQQ>
> .
>

2021-02-28 09:42 UTC, SimonYu-Web submitted a review, later dismissed
LGTM👍

2021-02-28 09:56 UTC, SimonYu-Web submitted a review, later dismissed

2021-02-28 23:01 UTC, KieraDOG commented
![image](https://user-images.githubusercontent.com/6457082/109436746-24143b00-7a75-11eb-9c9c-e6c2f5d6663a.png)
这个页面有问题

2021-02-28 23:09 UTC, KieraDOG requested changes

2021-02-28 23:09 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +const LargeInput = styled(Input)`
默认 Input 的 width 应该是 flex: 1，这里应该不传入 hard code 的 宽度，应该由 FormItem 控制

2021-02-28 23:09 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/Form.jsx
> +              <LargeInput
这里ziwei说的是对的，FormItem 里面有 layout flex, 我们给了定宽的 label， input flex 1 扩充剩下的空间，不应该再给 width

2021-02-28 23:09 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/components/InviteMemberModal/components/ContactContent/ContactContent.jsx
> +  margin: 32px 50px 16px;
？？？？

2021-02-28 23:09 UTC, KieraDOG commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +  margin-left:55px;
？？？？？ 做复用为什么会改这里的样式？

2021-02-28 23:09 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +      justify-content: flex-start;
需要这个吗？

2021-02-28 23:09 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +      margin: 10px 50px;
为什么有 x 轴 50px？

2021-02-28 23:09 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +      margin: 10px 50px;
难道以后所有的 Form 的 input 都要左右 50px 的 gap？那这个 reusable 也太差了

2021-02-28 23:09 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +  margin-top: 30px
30px 有点太大了吧？我记得我是做的 y 轴 的 12px

2021-02-28 23:09 UTC, KieraDOG commented on src/components/FormItem/FormItem.jsx
> +  <Form>
StyledFormItem

2021-02-28 23:10 UTC, KieraDOG commented
![image](https://user-images.githubusercontent.com/6457082/109436928-48244c00-7a76-11eb-9de9-e6cc7441a6ab.png)
label 和 input 没有水瓶对其

2021-03-01 00:42 UTC, merged