feat(reset-password): create reset password modal
melfish-lorem/1tds pull request #39
Opened 2021-03-02 00:31 UTC by SimonYu-Web

完成：
弹窗基本功能完成

还需要完善：
1.打开新窗口的同时旧窗口关闭
2.是否需要添加返回上一次弹窗

2021-03-02 09:45 UTC, KieraDOG submitted a review, later dismissed

2021-03-02 09:45 UTC, KieraDOG commented on src/app/Header/components/MenuRight/ForgetPassword/ForgetPassword.jsx
> +  );
```suggestion
  } = useForm(config);
```

2021-03-02 09:45 UTC, KieraDOG commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +  const [showForgetPasswordModal, setShowForgetPasswordModal] = useState(false);
这个 ziwei 和 维尼上期都做过 可以找他们 pair 下 @hachilam92 @JavaScriptN0ob

2021-03-02 23:44 UTC, hachilam92 commented on src/app/Header/components/MenuRight/Login/ForgetPwdModal/formConfig.js
> +function alertEmpty(label) {
可以从utils中import进行复用

2021-03-02 23:44 UTC, hachilam92 commented on src/app/Header/components/MenuRight/Login/ForgetPwdModal/formConfig.js
> +    getErrorMessage: (email) => (!email && alertEmpty(config.email.label))
可以参考“成为团长”表单的config，里面的getErrorMessage换成了新的写法

2021-03-02 23:44 UTC, hachilam92 commented on src/app/Header/components/MenuRight/Login/formConfig.js
> +function alertEmpty(label) {
同上

2021-03-02 23:44 UTC, hachilam92 commented on src/app/Header/components/MenuRight/Login/formConfig.js
> +    getErrorMessage: (email) => (!email && alertEmpty(config.email.label))
同上

2021-03-02 23:44 UTC, hachilam92 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +        <ForgetPwdModal onClose={() => setShowForgetPasswordModal()} />
似乎缩进不太对

2021-03-02 23:52 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +        <ForgetPwdModal onClose={() => setShowForgetPasswordModal()} />
这里应该是Header用了ul包了俩li，所以缩进看着怪怪的，但是好像没错

2021-03-03 03:39 UTC, SimonYu-Web commented
都改好了  可以merge

2021-03-03 03:55 UTC, hachilam92 commented on src/app/Header/components/MenuRight/Login/ForgetPwdModal/ForgetPwdModal.jsx
> +  );
```suggestion
  } = useForm(config);
```

2021-03-03 03:58 UTC, Jakeeeeeeeee approved these changes

2021-03-03 07:21 UTC, JavaScriptN0ob approved these changes
LGTM

2021-03-03 08:27 UTC, Nov66 approved these changes

2021-03-03 10:23 UTC, KieraDOG commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +export default function Login({ onClose, setShowForgetPasswordModal }) {
这个和 @hachilam92 @JavaScriptN0ob pair 过了吗？
```suggestion
export default function Login({ onClose, onShowForgetPassword }) {
```

2021-03-03 10:23 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +  const [showForgetPasswordModal, setShowForgetPasswordModal] = useToggler(false);
这个可以用个状态控制

2021-03-03 10:23 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +  const [showForgetPasswordModal, setShowForgetPasswordModal] = useToggler(false);
我现在没在电脑旁，你有空和 @hachilam92 @JavaScriptN0ob 过一下或者等我明天和你过一下

2021-03-03 10:37 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +export default function Login({ onClose, setShowForgetPasswordModal }) {
没跟我pair，不过我看他已经复用了子维 useToggler

2021-03-03 10:52 UTC, KieraDOG commented
可以用一个 state 控制不同的 modal 开关
2021年3月3日 +1100 21:37 Wenpei Zhang <notifications@github.com>，写道：
> @JavaScriptN0ob commented on this pull request.
> In src/app/Header/components/MenuRight/Login/Login.jsx:
> > @@ -16,7 +16,7 @@ const LoginButton = styled(Button)`
>
>   margin: 50px auto 28px;
>
> `;
>
>
>
> -export default function Login({ onClose }) {
>
> +export default function Login({ onClose, setShowForgetPasswordModal }) {
>
> 没跟我pair，不过我看他已经复用了子维 useToggler
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-03 14:04 UTC, SimonYu-Web commented on src/app/Header/components/MenuRight/Login/Login.jsx
> +export default function Login({ onClose, setShowForgetPasswordModal }) {
嗯 下午跟ziwei pair了一下

2021-03-03 23:17 UTC, KieraDOG requested changes

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +  const [showUserAuthModals, setShowUserAuthModals] = useToggler(false);
```suggestion
  const [showUserAuthModals, toggleShowUserAuthModals] = useToggler(false);
```

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/UserAuthModals/ForgetPwd/ForgetPwd.jsx
> +    }
@hachilam92 这是 ziwei 给大家留的坑，这里不需要 if else
```suggestion
    toggleTouched();
```

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/UserAuthModals/ForgetPwd/formConfig.js
> +function alertEmpty(label) {
这里已经做过 refactoring 了，去参考 login 或者 成为团长 写一下

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/UserAuthModals/Login/Login.jsx
> -        <Button variant="naked">忘记密码？</Button>
忘记密码入口呢？

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/UserAuthModals/Login/formConfig.js
> +import validator from 'validator';
同上，refactoring

2021-03-03 23:17 UTC, KieraDOG commented on src/app/Header/components/MenuRight/UserAuthModals/UserAuthModals.jsx
> +      {currentView === VIEW_SHARE_BY.LOGIN && (
你们怎么都写成这样了？

2021-03-04 04:50 UTC, Jakeeeeeeeee approved these changes

2021-03-04 04:51 UTC, KieraDOG approved these changes

2021-03-04 04:51 UTC, merged