Auth signup
melfish-lorem/1tds pull request #42
Opened 2021-03-02 13:16 UTC by jessieease

achieved:
1) validation: 每一个field不为空
2) validation: 验证email是否已经注册
3) validation: 验证email是否为有效格式
4) validation: 验证mobile是否为有效格式
5) encrypted password

2021-03-02 13:27 UTC, KieraDOG requested changes

2021-03-02 13:27 UTC, KieraDOG commented on src/pages/api/sign-up.js
>  const Users = require('../../db/models/users');
import

2021-03-02 13:27 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +    res.status(400).json({ message: 'Input can not be empty' });
```suggestion
    res.status(400).end();
```

2021-03-02 13:27 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +    // Store hash in your password DB.
Code as documentation

2021-03-02 13:27 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  const findEmail = await Users.findOne({ where: { email: req.body.email } });
```suggestion
  const conflictUser = await Users.findOne({ where: { email: req.body.email } });
```

2021-03-02 13:27 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +    console.log(result);
?

2021-03-02 13:28 UTC, KieraDOG commented
一些小问题 整体思路 👍

2021-03-02 13:28 UTC, KieraDOG commented
你这个是不是和 @jessieease 做的重复了？

2021-03-02 13:28 UTC, jessieease commented on src/pages/api/sign-up.js
> +    console.log(result);
40行已删

2021-03-02 13:29 UTC, KieraDOG commented
哦哦哦哦 都是你的 PR 那你把之前那个 close 掉吧

2021-03-02 13:30 UTC, KieraDOG commented
还有就是 req.body 一直在重复使用 要不要提前解构？

2021-03-02 13:32 UTC, jessieease commented on src/pages/api/sign-up.js
>  const Users = require('../../db/models/users');
已更新

2021-03-02 13:34 UTC, jessieease commented on src/pages/api/sign-up.js
> +    // Store hash in your password DB.
✅get

2021-03-02 13:35 UTC, jessieease commented on src/pages/api/sign-up.js
> +  const findEmail = await Users.findOne({ where: { email: req.body.email } });
已换

2021-03-02 13:40 UTC, jessieease commented on src/pages/api/sign-up.js
> +    res.status(400).json({ message: 'Input can not be empty' });
当前改好👌，其他的error message需要都换成end()吗

2021-03-02 13:55 UTC, jessieease commented
> 还有就是 req.body 一直在重复使用 要不要提前解构？

要！！但是晚上跟子维商量了一下暂时没想到特别好的办法，现在脑子有点儿不转了，明天再想想

2021-03-02 23:29 UTC, JavaScriptN0ob commented on src/pages/api/sign-up.js
> +  const initUser = {
```
const {
  mobile,
  email,
  address,
  password,
} = req.body;

const initUser = { mobile, email, address, pasword };
```
上面用了obj initUser里是 key value同名的写法 @ @jessieease

2021-03-02 23:29 UTC, JavaScriptN0ob commented on src/pages/api/sign-up.js
> +    };
这里直接调用上面就好啦

2021-03-02 23:35 UTC, hachilam92 commented on src/pages/api/sign-up.js
>    };
目前可以写成
 `const｛ mobile, email, address, password ｝= req.body;`
`const initUser = { mobile, email, address, password };`
之后我们可以考虑提取出来写成dto和mapper

2021-03-02 23:36 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  const initUser = {
```suggestion
  const requestData = {
```

2021-03-02 23:37 UTC, JavaScriptN0ob commented on src/pages/api/sign-up.js
>    };
嘿嘿，快了5分钟

2021-03-03 00:25 UTC, jessieease commented on src/pages/api/sign-up.js
> +  const initUser = {
👍我火速前去

2021-03-03 11:14 UTC, hachilam92 approved these changes
LGTM

2021-03-03 11:16 UTC, jessieease commented
hold on各位，我还差一个feature

2021-03-03 23:09 UTC, KieraDOG requested changes

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  const requestData = {
注意空行
```suggestion
  } = req.body;
  
  const requestData = {
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  if (!isMobilePhone(requestData.mobile, 'en-AU')) {
```suggestion
  if (!isMobilePhone(mobile, 'en-AU')) {
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  if (!isEmail(requestData.email)) {
```suggestion
  if (!isEmail(email)) {
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  const conflictUser = await Users.findOne({ where: { email: requestData.email } });
```suggestion
  const conflictUser = await Users.findOne({ where: { email } });
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +  hash(requestData.password, 10, async (err, hashedPassword) => {
```suggestion
  hash(password, 10, async (err, hashedPassword) => {
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +    await Users.create(result);
```suggestion
    await Users.create({ ...requestData, password: hashedPassword });
```

2021-03-03 23:09 UTC, KieraDOG commented on src/pages/api/sign-up.js
> +    res.json({ authToken: token });
没有说需要做 JWT 啊，没有说需要做 JWT 啊，没有说需要做 JWT 啊！！！

2021-03-04 02:09 UTC, jessieease commented on src/pages/api/sign-up.js
> +  const requestData = {
okk

2021-03-04 02:10 UTC, jessieease commented on src/pages/api/sign-up.js
> +  if (!isMobilePhone(requestData.mobile, 'en-AU')) {
已改

2021-03-04 02:17 UTC, jessieease commented on src/pages/api/sign-up.js
> +  if (!isEmail(requestData.email)) {
改+11111

2021-03-04 02:19 UTC, jessieease commented on src/pages/api/sign-up.js
> +  const conflictUser = await Users.findOne({ where: { email: requestData.email } });
soooo cool

2021-03-04 02:19 UTC, jessieease commented on src/pages/api/sign-up.js
> +  hash(requestData.password, 10, async (err, hashedPassword) => {
改！

2021-03-04 02:24 UTC, jessieease commented on src/pages/api/sign-up.js
> +    await Users.create(result);
这里是因为readable的原因嘛 最好用{ ...requestData, password: hashedPassword } instead of 调个result去找

2021-03-04 02:25 UTC, jessieease commented on src/pages/api/sign-up.js
> +    res.json({ authToken: token });
！！！迅速改了（严肃脸

2021-03-04 02:28 UTC, jessieease commented on src/pages/api/sign-up.js
> +    await Users.create(result);
我看懂了！！只有hashedPassword改了 其他的都没变 所以这样写更好👍

2021-03-04 03:15 UTC, KieraDOG requested changes

2021-03-04 03:15 UTC, KieraDOG commented on src/db/migrations/20210303105045-create-verifications.js
> +        type: Sequelize.STRING,
创建一个 新的 migration token `allowNull: false`

2021-03-04 03:53 UTC, merged