feat(SendEmailModal): introduce Send Email Modal
melfish-lorem/1tds pull request #45
Opened 2021-03-03 14:28 UTC by Nov66

Achieved:

- 在邀请团员 Modal 中点击“完成注册”时，从“邀请团员" Modal 跳转至“验证邮箱已发送” Modal

- 在“验证邮箱" Modal 中，点击“重新注册”时，关闭 Modal 并回到“成为团长页面”

2021-03-03 23:04 UTC, KieraDOG requested changes

2021-03-03 23:04 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/components/InviteMemberModal/InviteMemberModal.jsx
> +      )}
SendEmailModal 应该是全新的 Modal， 逻辑上应该和 InviteMemberModal 解偶，所以我认为 onSubmit 应该先关掉 InviteMemberModal，然后打开 SendEmailModal， 而不是写在一起

2021-03-03 23:04 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/components/InviteMemberModal/components/SentEmailContent/SentEmailContent.jsx
> +export default function LinkContent({ onClose }) {
LinkContent？

2021-03-03 23:04 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/components/InviteMemberModal/components/SentEmailContent/SentEmailContent.jsx
> +import React from 'react';
这应该是一个全新的 Modal，这样这个 Modal 我可以在以后任何地方复用

2021-03-03 23:04 UTC, KieraDOG commented on src/app/BecomeACaptainPage/components/Form/components/InviteMemberModal/components/SentEmailContent/SentEmailContent.jsx
> +        验证邮箱已发送到你的邮箱 xxx@xxx.com,
需要再建一张卡， flow user email to SendEmailModal

2021-03-04 04:18 UTC, Jakeeeeeeeee approved these changes

2021-03-04 04:18 UTC, merged