Email verify api
melfish-lorem/1tds pull request #51
Opened 2021-03-04 13:24 UTC by hachilam92

已完成：
1. 添加verify email接口，通过query中的token检索user并更新其状态为ACTIVE
2.  不论结果，返回201
3. 修复api路径中遗漏的auth

2021-03-04 13:57 UTC, Jakeeeeeeeee approved these changes

2021-03-04 16:11 UTC, KieraDOG approved these changes

2021-03-04 16:11 UTC, KieraDOG commented on src/pages/api/auth/verify-email.js
> +    res.status(201).end();
这里返回 404 吧 方便 dbug 也不会暴露安全细节

2021-03-04 22:51 UTC, hachilam92 commented on src/pages/api/auth/verify-email.js
> +    res.status(201).end();
好的

2021-03-04 23:02 UTC, KieraDOG requested changes

2021-03-04 23:02 UTC, KieraDOG commented on src/utils/userStatus/userStatus.js
> +const USER_STATUS = {
不需要这个文件，我写个 Comment 你参考一下

2021-03-04 23:02 UTC, KieraDOG commented on src/pages/api/auth/verify-email.js
> +  await user.save();
```suggestion
  await user.verifyEmail();
```

2021-03-04 23:05 UTC, KieraDOG commented
https://sequelize.org/master/manual/model-basics.html#taking-advantage-of-models-being-classes

src/db/models/users.js
```
class Users extends Model {
  async verifyEmail() {
    if (this.status !== 'PENDING_VERIFICATION') {
      return;
    }

    this.status = 'ACTIVE';

    await this.save();
  }
}
```

2021-03-04 23:32 UTC, hachilam92 commented on src/pages/api/auth/verify-email.js
> +  const user = await Users.findOne({ where: { id: UserId } });
好的，我再改改

2021-03-04 23:36 UTC, JavaScriptN0ob commented on src/pages/api/auth/verify-email.js
> +  await user.save();
这是要提出去写的意思吗 ↓

2021-03-05 00:05 UTC, hachilam92 commented on src/pages/api/auth/verify-email.js
> +  await user.save();
Users这个类里面的方法是大概对应repository层吗

2021-03-05 04:13 UTC, closed without merging