Mobile header (responsive)
melfish-lorem/1tds pull request #56
Opened 2021-03-08 06:34 UTC by Nov66

Achieved:

- 实现 375px-768px 页面的 responsive
- 点击 burger 按钮滑出菜单左栏

Question:

- Button 组件下的 medium size 下加了 media 实现 responsive，其他 size 包括 input 是否也要添加来实现responsive？

2021-03-08 07:24 UTC, Jakeeeeeeeee reviewed
感觉导航栏点击出来的时候有点生硬，加下transition可以会好一些

2021-03-08 07:25 UTC, Nov66 commented
> 感觉导航栏点击出来的时候有点生硬，加下transition可以会好一些

马上改！

2021-03-08 15:00 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +const LoginButton = styled.li`
好像也没啥讲究 我当时做的时候把它想成整个 header 都是 ul 了 后来拆分的时候就还是 li 了

2021-03-08 15:00 UTC, Nov66 commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +      <Left onClick={handleClick} showDropDownMenu={showDropDownMenu}>
好改！改成 leftitem 和 rightitem

2021-03-08 15:03 UTC, Nov66 commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
试了下 感觉好像没有从左边出来美观

2021-03-08 15:04 UTC, Jakeeeeeeeee commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +const LoginButton = styled.li`
哦哦,，那可能div会好一点？ li 感觉有点不是是很readable

2021-03-08 15:10 UTC, Jakeeeeeeeee commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
感觉印象中的导航栏都是从上面往下面出来的，可以和凯泉或者龙哥确认下

2021-03-08 15:11 UTC, Nov66 commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
等下 好像不能那么简单的实现从上到下 可能难道也许我要做成 dropdown menu 才可以？如果要从上到下的话我明天起来得重新看看

2021-03-08 15:17 UTC, Jakeeeeeeeee commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
width:0;
top: ${({ showSlideMenu }) => (showSlideMenu ? 45px : '-100%')};
不知道这样行不行

2021-03-08 15:19 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +const LoginButton = styled.li`
发现右边如果只有搜索和登陆的话 可以不用 ul 已改 之前没注意这个问题

2021-03-08 15:22 UTC, Jakeeeeeeeee commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
```suggestion
    width: 0;
    top: ${({ showSlideMenu }) => (showSlideMenu ? 45px : '-100%')};
```
试试这样呢，或者明天早会问问龙哥有没有更好的方法

2021-03-08 15:35 UTC, Nov66 commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
不行 就是这样改的话 他都是从最上面出来 按道理如果是从上往下应该是从那个 burger 按钮的下方出来 如果要从上到下的话我可能要重新想下

2021-03-08 22:50 UTC, KarlokCheung reviewed
发现header在Chrome里选iPhone后没有撑满页面
看了下devTool没有什么问题，会不会是Container的尺寸没有responsive？

![header-iPhone](https://user-images.githubusercontent.com/70373704/110392230-b68f8c80-80bc-11eb-9608-dad619c51299.png)

2021-03-08 23:59 UTC, KieraDOG requested changes

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/Logo/Logo.jsx
> +  }
为什么不再手机上直接缩小 Logo, 而是再做一个 Container 出来？

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
不需要效果，直接 display 就好，动画的话以后再说

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +  }
这个 Item 在 mobile 是不需要显示的，我们还需要这个 padding 吗？

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +  }
哦哦，我看懂你的设计了，这样过于复杂了，没必要让 mobile 状态复用这块逻辑， dropdown 直接写一个新的就可以了

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +    align-items: center;
为什么 CTA 在 mobile状态下需要用 flex 居中？

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +import ResponsiveSearchButton from './components/ResponsiveSearchButton/ResponsiveSearchButton';
这个需要拆除去吗？

2021-03-08 23:59 UTC, KieraDOG commented on src/app/Header/components/MenuRight/components/ResponsiveSearchButton/ResponsiveSearchButton.jsx
> +    height: 20px;
Button 本身就有大小了吧，这里还需要单独设置吗？

2021-03-08 23:59 UTC, KieraDOG commented on src/components/Container/Container.jsx
> +  }
👍

2021-03-09 01:04 UTC, Nov66 commented on src/app/Header/components/Logo/Logo.jsx
> +  }
之前是因为那个袋鼠是用next/image import进来 加上外面又包了一个半圆 不能直接缩小logo

2021-03-09 01:08 UTC, Nov66 commented
> 发现header在Chrome里选iPhone后没有撑满页面
> 看了下devTool没有什么问题，会不会是Container的尺寸没有responsive？
> 
> ![header-iPhone](https://user-images.githubusercontent.com/70373704/110392230-b68f8c80-80bc-11eb-9608-dad619c51299.png)

这个我之前也发现了 可能是因为下面页面的有些东西没做 responsive 把他画面撑出去了 之后页面如果也做了 responsive 应该没有这个问题了？

2021-03-09 01:14 UTC, KieraDOG commented
> 发现header在Chrome里选iPhone后没有撑满页面
> 看了下devTool没有什么问题，会不会是Container的尺寸没有responsive？
> 
> ![header-iPhone](https://user-images.githubusercontent.com/70373704/110392230-b68f8c80-80bc-11eb-9608-dad619c51299.png)

应该是这个页面其他地方的 responsive 还没做好
所以其他地方撑开了宽度

2021-03-09 01:16 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +import ResponsiveSearchButton from './components/ResponsiveSearchButton/ResponsiveSearchButton';
因为手机不是去掉 input 框 我就单独做了个搜索icon的出来

2021-03-09 01:17 UTC, Nov66 commented on src/app/Header/components/MenuRight/components/ResponsiveSearchButton/ResponsiveSearchButton.jsx
> +    height: 20px;
这里确实不需要了 已改

2021-03-09 01:25 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +    align-items: center;
这个是我之前调整的时候加的 后来不需要这个的时候忘记删掉了 已改

2021-03-09 10:04 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
@Jakeeeeeeeee  css modules有一个classnames package，通过import classnames/bind来解决这个。不过目前SC写法很简单高效易读

2021-03-09 10:04 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +import ResponsiveSearchButton from './components/ResponsiveSearchButton/ResponsiveSearchButton';
``<input variant = ‘naked’ />``

2021-03-09 10:45 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +import ResponsiveSearchButton from './components/ResponsiveSearchButton/ResponsiveSearchButton';
对哦 可以这样写 
```
<Input
        variant="naked"
        suffix={(
          <Image
            alt="搜索"
            src="/images/icons/searchIcon.svg"
            width={20}
            height={20}
          />
        )}
      />
```
但是这样写 suffix 的话后面这个只留下搜索的 icon 可以做后续的功能吗

2021-03-09 10:58 UTC, JavaScriptN0ob commented
我先mark一下，等龙哥来讲over engineering。
后续功能可以扩展Input里的suffix传url之类的。

Shengyan Liu <notifications@github.com>于2021年3月9日 周二21:46写道：

> *@Nov66* commented on this pull request.
> ------------------------------
>
> In src/app/Header/components/MenuRight/MenuRight.jsx
> <https://github.com/melfish-lorem/1tds/pull/56#discussion_r590207505>:
>
> > @@ -5,46 +5,60 @@ import Button from '../../../../components/Button';
>
>  import Input from '../../../../components/Input';
>
>  import useToggler from '../../../../hooks/useToggler';
>
>  import UserAuthModals from './components/UserAuthModals';
>
> +import ResponsiveSearchButton from './components/ResponsiveSearchButton/ResponsiveSearchButton';
>
>
> 对哦 可以这样写
>
> <Input
>
>         variant="naked"
>
>         suffix={(
>
>           <Image
>
>             alt="搜索"
>
>             src="/images/icons/searchIcon.svg"
>
>             width={20}
>
>             height={20}
>
>           />
>
>         )}
>
>       />
>
>
> 但是这样写 suffix 的话后面这个只留下搜索的 icon 可以做后续的功能吗
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/melfish-lorem/1tds/pull/56#discussion_r590207505>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEIKGDDZPYTRNVELOZU55LTCX36VANCNFSM4YYZUW4A>
> .
>

2021-03-09 15:49 UTC, Jakeeeeeeeee commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +    left: ${({ showSlideMenu }) => (showSlideMenu ? 0 : '-100%')};
@JavaScriptN0ob 噢噢 知道了

2021-03-09 15:53 UTC, Jakeeeeeeeee approved these changes

2021-03-10 23:43 UTC, KieraDOG requested changes

2021-03-10 23:43 UTC, KieraDOG commented on src/app/Header/components/Logo/Logo.jsx
> +  }
这个需要吗？

2021-03-10 23:43 UTC, KieraDOG commented on src/app/Header/components/ResponsiveBurgerMenu/ResponsiveBurgerMenu.jsx
> +    <>
在 responsive 情况下 BurgerMenu 的高度应该是 logo 高度的一半，也就是 40px

2021-03-10 23:43 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> -  height: 64px;
不要把高度删掉，我写这个高度是为了让 logo 居中，logo 高 128px, 所有 header 其他元素高 64px 这样就实现了 Logo  只有一半在 Header 里面

2021-03-10 23:43 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +  @media (min-width: 320px) and (max-width: 1024px) {
和之前 ResponsiveBurgerMenu 一样，手机情况下 高度 40px

2021-03-10 23:43 UTC, KieraDOG commented on src/app/Header/Header.jsx
> +        <ResponsiveBurgerMenu />
ResponsiveBurgerMenu 应该放在 MenuLeft 里面，在手机上它也是左半部分的内容

2021-03-11 03:03 UTC, Nov66 commented on src/app/Header/components/Logo/Logo.jsx
> +  }
这个不要的话 缩小页面的时候 logo 就会跑到最左边去

2021-03-11 03:10 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> -  height: 64px;
明白了

2021-03-11 03:18 UTC, Nov66 commented on src/app/Header/Header.jsx
> +        <ResponsiveBurgerMenu />
好的！已改！

2021-03-11 10:53 UTC, KieraDOG reviewed
我明天和你一起过一下吧

2021-03-11 10:53 UTC, KieraDOG commented on src/app/Header/components/Logo/Logo.jsx
> +    left: 50%;
这个应该还是可以继续用 desktop 的设计 left 和 right flex 1， logo 自然就居中了

2021-03-11 10:53 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
>  const Item = styled.li`
```suggestion
const LeftNav = styled.ul`
  flex: 1;
  height: 64px;
  list-style: none;
  margin: 0;
  display: flex;
  align-items: center;

  @media (min-width: 320px) and (max-width: 1024px) {
    height: 40px;
  }
`;

const Item = styled.li`
 @media (min-width: 320px) and (max-width: 1024px) {
    display: none;
  }
```

2021-03-11 10:53 UTC, KieraDOG commented on src/app/Header/components/MenuLeft/components/ResponsiveBurgerMenu/components/ResponsiveMenuLeft.jsx
> +const LeftNav = styled.ul`
这里直接叫 Nav 好一些？

2021-03-11 14:43 UTC, Nov66 commented on src/app/Header/components/MenuLeft/components/ResponsiveBurgerMenu/components/ResponsiveMenuLeft.jsx
> +const LeftNav = styled.ul`
好的！但是这个其实也只有左边部分 会不会不太好

2021-03-12 01:42 UTC, Jakeeeeeeeee approved these changes

2021-03-12 01:54 UTC, Jakeeeeeeeee approved these changes

2021-03-12 01:55 UTC, KieraDOG approved these changes

2021-03-12 01:55 UTC, Jakeeeeeeeee approved these changes

2021-03-12 02:01 UTC, merged