Simon/captain profile
melfish-lorem/1tds pull request #57
Opened 2021-03-08 13:17 UTC by SimonYu-Web

完成部分:
团长资料页面

接下来的工作：
增加切换卡片功能
根据UI设计完善User及icon位置

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/CaptainProfilePage.jsx
> +  height: 1000px;
height可能不需要hardcode?

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  background-color: #EB9050;
button>组件里有这个background-color，不需要重新写一次

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +                readOnly
如果input内容是readonly，那还需要validation吗？ 需要问一下龙哥

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +                  />
感觉有点过于设计咯。 邮箱应该是不能改的，只能read,所以不需要validation。修改密码有弹窗，所以这里也不需要validation。可能直接写两个input比较readable?

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileContent/PersonalInfo/config.js
> +export default config;
同上，感觉这里不需要validation

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileContent/ProfileContent.jsx
> +  box-sizing: border-box;
应该不需要写这个？global里有

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileNav/ProfileNav.jsx
> +    box-sizing: border-box;
应该不需要写这个？

2021-03-08 14:48 UTC, Jakeeeeeeeee commented on src/app/CaptainProfilePage/components/ProfileNav/ProfileNav.jsx
> +const ProfileNavContainer = styled(Container)`
感觉左边的sidebar不需要复用container?  container是一个width:1280px的复用组件，应该用给整个页面

2021-03-08 15:02 UTC, KieraDOG commented
@Jakeeeeeeeee 👍 review 非常棒 很专业

2021-03-08 15:02 UTC, KieraDOG commented
页面路由改为 /user/profile

2021-03-08 15:45 UTC, Nov66 commented on src/app/CaptainProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +                readOnly
确实好像如果都是通过弹窗来修改的话  这里应该是不需要validation？

2021-03-08 22:31 UTC, KarlokCheung commented on src/app/CaptainProfilePage/CaptainProfilePage.jsx
> +  height: 1000px;
同意，或者用vh?

2021-03-08 22:34 UTC, KarlokCheung reviewed
all good

2021-03-08 23:46 UTC, SimonYu-Web commented on src/app/CaptainProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +                  />
👍

2021-03-08 23:47 UTC, SimonYu-Web commented on src/app/CaptainProfilePage/components/ProfileNav/ProfileNav.jsx
> +const ProfileNavContainer = styled(Container)`
其实只用了container的margin: 0 auto  不用container也行

2021-03-08 23:50 UTC, SimonYu-Web commented on src/app/CaptainProfilePage/CaptainProfilePage.jsx
> +  height: 1000px;
这里需要定高  我试过用margin或者padding实现  背景拉不起来   用vh和px好像并没有什么区别

2021-03-09 00:02 UTC, KieraDOG requested changes

2021-03-09 00:02 UTC, KieraDOG commented on src/app/CaptainProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +                  />
readonly 也不需要 onChange 和 error 吧？

2021-03-09 00:02 UTC, KieraDOG commented on src/app/CaptainProfilePage/components/ProfileContent/PersonalInfo/config.js
> +import validator from 'validator';
这里需要这个 config 吗？

2021-03-09 00:02 UTC, KieraDOG commented on src/app/CaptainProfilePage/components/ProfileNav/ProfileNav.jsx
> +const ProfileNavContainer = styled(Container)`
那就不用 Container

2021-03-09 00:02 UTC, KieraDOG commented on src/components/Input/Input.jsx
> +    background-color: #FCEAC6;
这样直接改有没有影响之前已经做好的设计？

2021-03-09 00:03 UTC, SimonYu-Web commented on src/components/Input/Input.jsx
> +    background-color: #FCEAC6;
这个是全X新出的设计  黄色背景默认readonly

2021-03-09 07:06 UTC, hachilam92 commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  font-family: 'ZCOOL KuaiLe';
可以复用Heading

2021-03-09 07:06 UTC, hachilam92 commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  flex-direction: row;
row是默认值，应该不用额外加

2021-03-09 07:06 UTC, hachilam92 commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  flex-direction: row;
同上

2021-03-09 07:06 UTC, hachilam92 commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +`;
Button的样式最好还是通过attribute控制，如果是新样式的话可以往Button里面添加

2021-03-09 09:41 UTC, SimonYu-Web commented
新入口：
https://1tds-dt4qp0lv5-melfish.vercel.app/user/profile

2021-03-09 09:48 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +          <Input readOnly value={value} />
mobile 和地址修改的功能后面有卡是吧？

2021-03-09 09:48 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +          {key === 'password' ? (
这就不要用 map 了，一共两个，还有一个 if。直接手写好一些

2021-03-09 09:48 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +`;
对 不应该手动指定button 的字体大小 应该调用 size

2021-03-09 09:52 UTC, KieraDOG approved these changes
整体 Ok 剩下几个小问题改一下就好了

2021-03-09 10:01 UTC, JavaScriptN0ob commented on src/components/Button/Button.jsx
> +    navActive: css`
这里要不做个naked 背景色透明的button然后通过调用的时候加个container改变背景色。这里直接添加nav & navActive有点把button跟你做的profilePage偶合在一起了

2021-03-09 10:04 UTC, KieraDOG commented
绿色的 直接做一个 success variant 就好了
2021年3月9日 +1100 21:01 Wenpei Zhang <notifications@github.com>，写道：
> @JavaScriptN0ob commented on this pull request.
> In src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx:
> > @@ -0,0 +1,60 @@
>
> +import React from 'react';
>
> +import styled from 'styled-components';
>
> +import FormItem from '../../../../../components/FormItem';
>
> +import Input from '../../../../../components/Input';
>
> +import Button from '../../../../../components/Button';
>
> +import Heading from '../../../../../components/Heading';
>
> +
>
> +const UserInfoContainer = styled.div`
>
> +  width: 75%;
>
> 这里是父dom的 75 下面子组件是这个组件的60%，可能到时候responsive缩小之后可能就么得了
> In src/components/Button/Button.jsx:
> > @@ -41,6 +41,14 @@ const Button = styled.button`
>
>       background: #97A73F;
>
>       color: #ffffff;
>
>     `,
>
> +    navActive: css`
>
> 这里要不做个naked 背景色透明的button然后通过调用的时候加个container改变背景色。这里直接添加nav & navActive有点把button跟你做的profilePage偶合在一起了
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-09 10:49 UTC, SimonYu-Web commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +          <Input readOnly value={value} />
对的

2021-03-09 10:52 UTC, SimonYu-Web commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 75%;
那只能responsive的时候改了  根据UI的design应该只能这么实现？ 还是说想让我定宽好一些？

2021-03-09 10:52 UTC, SimonYu-Web commented on src/components/Button/Button.jsx
> +    navActive: css`
可以  我做个naked

2021-03-09 23:57 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 75%;
定宽

2021-03-09 23:58 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    `,
这个是哪个用的？这个颜色不是 primary 颜色？

2021-03-09 23:59 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    `,
这里已经有 naked 了

2021-03-09 23:59 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    success: css`
把 success 放到 color 里面去

2021-03-10 01:13 UTC, SimonYu-Web commented on src/components/Button/Button.jsx
> +    `,
但是字体颜色不一样
这个是用给nav中没有激活的button

2021-03-10 23:46 UTC, KieraDOG requested changes
所有百分比的width都要改一下，同时 master 上有很多新更新，要 merge 一下。

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 75%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 100%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  width: 75%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  width: 100%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  width: 100%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/ProfileContent.jsx
> +  width: 70%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +    width:30%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +    width: 80%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +    width: 80%;
不应该出现百分比的 width

2021-03-10 23:46 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    successVariant: css`
这个和 success 的区别是什么，为什么要新建一个？

2021-03-10 23:46 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +    `,
。。。这个细微区别就没必要 follow 了，不需要 nav 这个，直接用 primary 就好了

2021-03-11 01:55 UTC, KieraDOG requested changes

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 400px;
这个宽度没必要把

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  width: 500px;
这个也没必要吧

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  width: 400px;
同没必要?

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  width: 500px;
同没必要?

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +const Title = styled(Heading)`
要不要抽出来复用？

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  margin: 0 auto;
需要居中吗？

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +    justify-content: center;
缩进

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +    width: 300px;
缩进

2021-03-11 01:55 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileNav/ProfileNav.jsx
> +const OptionButton = styled(Button)`
这里不需要分开两个Button 写，同一个 Button 有 margin 就可以了

2021-03-11 01:55 UTC, KieraDOG commented on src/components/Button/Button.jsx
> +  }[props.color || 'primary'])}
最新的 Button 没有 props.color 了

2021-03-11 02:49 UTC, SimonYu-Web commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +const Title = styled(Heading)`
我觉得不需要  主要  两个样式还是不太一样

2021-03-11 04:03 UTC, hachilam92 submitted a review, later dismissed
LGTM

2021-03-11 04:42 UTC, KieraDOG requested changes

2021-03-11 04:42 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  padding: 12px;
这个css情况下 padding-bottom 不工作

2021-03-11 04:42 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/BusinessInfo/BusinessInfo.jsx
> +  margin-right: 280px;
这个做个 flex container 在外面 然后 justify content space between 好一些

2021-03-11 04:42 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  margin: 0 auto;
这里的 auto 我没太看懂，一般是定宽的东西给 auto 做水平居中效果，你这个 auto 没有定宽是为了？

2021-03-11 04:42 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  margin: 0 auto;
同上

2021-03-11 04:42 UTC, KieraDOG commented on src/app/UserProfilePage/components/ProfileContent/PersonalInfo/PersonalInfo.jsx
> +  padding: 0 10px 30px;
4的倍数？

2021-03-11 05:28 UTC, KieraDOG approved these changes

2021-03-11 05:29 UTC, merged