feat(verifyEmail): add apis/verifyEmail
melfish-lorem/1tds pull request #73
Opened 2021-03-10 13:13 UTC by Nov66

2021-03-10 23:37 UTC, KieraDOG requested changes

2021-03-10 23:37 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
不要 disable 这个 rule，如果出现这个 warning 说明代码有问题

2021-03-10 23:37 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +      console.log(error);
建一张卡做邮箱验证失败

2021-03-11 02:57 UTC, Nov66 commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
好的 已改

2021-03-11 04:50 UTC, KieraDOG submitted a review, later dismissed

2021-03-11 04:53 UTC, merged