auth/forget-password
melfish-lorem/1tds pull request #74
Opened 2021-03-10 15:59 UTC by jessieease

1) 寻找email 返回400
2) 寻找user 都返回201
3) scope换成’RESET_PASSWORD‘, 为reset-password做准备

2021-03-10 23:34 UTC, KieraDOG commented on src/app/Header/components/MenuRight/components/UserAuthModals/UserAuthModals.jsx
> +import React, { useState } from 'react';
pull 一下 master？ 这个文件被移到外面去了

2021-03-10 23:35 UTC, KieraDOG requested changes

2021-03-10 23:35 UTC, KieraDOG commented on src/controllers/auth/forgetPassword/forgetPassword.js
> +  await mail.sendEmailVerification(email, token);
`sendEmailVerification` 是发送验证邮箱邮件

```suggestion
  await mail.sendResetPassword(email, token);
```

2021-03-11 01:47 UTC, jessieease commented on src/controllers/auth/forgetPassword/forgetPassword.js
> +  await mail.sendEmailVerification(email, token);
好了!

2021-03-11 04:54 UTC, KieraDOG approved these changes

2021-03-11 04:55 UTC, merged