Shengyanliu/ch407/loading
melfish-lorem/1tds pull request #82
Opened 2021-03-14 08:23 UTC by Nov66

- 添加了没有圆包裹的 logo （纯袋鼠logo）
- 居中了邮箱验证成功页面
- 添加了 LoadingState 页面

2021-03-14 09:55 UTC, hachilam92 commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  position: absolute;
这里感觉有点奇怪，为什么一个页面的container会需要absolute定位呢

2021-03-14 09:55 UTC, hachilam92 commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
>    const [loading, setloading] = useState(true);
setloading应该写成setLoading

2021-03-14 10:44 UTC, Jakeeeeeeeee commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  position: absolute;
如果不用absolute定位，可以用margin:auto 实现居中

2021-03-14 10:44 UTC, Jakeeeeeeeee commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +  position: absolute;
这里也是 margin:auto也是实现居中，但具体可以问问龙哥用哪种方式

2021-03-14 10:47 UTC, Nov66 commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  position: absolute;
不行 我重新提交了一个 增加了高度

2021-03-14 10:55 UTC, Nov66 commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +  position: absolute;
哈哈我用的是龙哥上周四课上讲的方法 感觉也行？

2021-03-14 12:29 UTC, hachilam92 commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +const Overlay = styled.div`
Overlay可以考虑对Modal里面的Overlay进行复用

2021-03-14 14:11 UTC, Nov66 commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +const Overlay = styled.div`
那把overlay单独做一个公共组件出来？

2021-03-14 23:21 UTC, KieraDOG approved these changes

2021-03-14 23:21 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +const Overlay = styled.div`
嗯 Overlay 抽到 components 里面去

2021-03-14 23:21 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  height: 724px;
不需要高度，就有一段 margin top 就可以了

2021-03-15 13:05 UTC, Nov66 commented on src/app/EmailVerifySuccessPage/EmailVerifySuccessPage.jsx
> +  height: 724px;
好的！已改！

2021-03-16 00:58 UTC, KieraDOG requested changes

2021-03-16 00:58 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +          请不要进行操作
```suggestion
          正在激活您的账号，请耐心等待。
```

你这个说的也太吓人了

2021-03-16 00:58 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +        <Heading size="lg">正在加载</Heading>
```suggestion
        <Heading size="lg">激活账号</Heading>
```

2021-03-16 00:58 UTC, KieraDOG commented on src/app/EmailVerifySuccessPage/components/LoadingState/LoadingState.jsx
> +      <Icon spin variant="naked" name="loading" size="6x" />
```suggestion
      <Icon spin variant="naked" name="loading" size="3x" />
```

小一点好看些

2021-03-16 01:05 UTC, KieraDOG submitted a review, later dismissed

2021-03-16 01:15 UTC, KieraDOG approved these changes

2021-03-16 01:15 UTC, merged