forget password api
melfish-lorem/1tds pull request #83
Opened 2021-03-14 08:34 UTC by jessieease

已完成：

1. 在env.local.example添加了'JWT_SECRET=' 确保本地环境测试成功
2. call 忘记密码页面的api 
3. 添加忘记密码页面的success信息

2021-03-14 10:05 UTC, hachilam92 commented
记得pull最新的代码呀

2021-03-14 10:08 UTC, jessieease commented
> 记得pull最新的代码呀
好的呀

2021-03-14 11:02 UTC, Jakeeeeeeeee reviewed
记得检查一下这个push的版本可不可以正常发邮件哦

2021-03-14 11:03 UTC, Nov66 reviewed
为啥会有两个 empty file

2021-03-14 23:15 UTC, KieraDOG requested changes
你把 icloud 字体文件给 commit 进来了

2021-03-14 23:18 UTC, KieraDOG requested changes

2021-03-14 23:18 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
catch 之后也有 setHettpRequest？

2021-03-14 23:18 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        {emailSent ? (
这个的 用户场景是？
点击确定后确定按钮变成重置密码？不是很对吧

2021-03-15 06:31 UTC, jessieease commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        {emailSent ? (
删掉删掉！！

2021-03-16 00:55 UTC, KieraDOG approved these changes
小问题改一下就好了

2021-03-16 00:55 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
```suggestion
```

这里不需要 return 把，请求失败也应该要 setSubmitting false, 这样用户才能继续操作

2021-03-16 00:58 UTC, jessieease commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
好的

2021-03-16 01:01 UTC, jessieease commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
但龙哥 这里有一个问题 forgetPassword这个后端只根据用户邮箱输入不正确返回400，以及找不找得到user都是201相当于没有错误 所以还需要setSubmitting false么

2021-03-16 01:06 UTC, jessieease commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
相当于catch400的error 也允许用户继续操作吗

2021-03-16 01:07 UTC, KieraDOG commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
需要，万一以后后端加逻辑呢？你这里应该做好 Open Close 原则，就是自己的内部逻辑自己维护，不去依赖后端的具体实现

2021-03-16 01:08 UTC, jessieease commented on src/app/ForgetPasswordModal/ForgetPasswordModal.jsx
> +        return;
好的 open close！！记小本本上

2021-03-16 01:11 UTC, KieraDOG approved these changes

2021-03-16 01:11 UTC, merged