feat(ModalPage): add ModalPage and ResetPasswordPage(static)
melfish-lorem/1tds pull request #84
Opened 2021-03-14 10:05 UTC by KarlokCheung

Achieve: 

1. add ModalPage component
2. add ResetPasswordPage(static)

2021-03-14 10:16 UTC, hachilam92 commented on src/components/ModalPage/ModalPage.jsx
> +const Overlay = styled.div`
感觉是不是可以把Modal里面的Overlay抽出来在这里复用

2021-03-14 11:20 UTC, Jakeeeeeeeee commented on src/components/ModalPage/ModalPage.jsx
> +      <Header />
不知道Header可不可以直接写在这里面，不用单独写一个component，感觉这个component内的代码不算太多

2021-03-14 23:11 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +  <ModalPage title="重置密码" footer="*该链接仅24小时有效">
这里 footer 的内容不对，其次，感觉 ModalPage 不需要 footer 呀

2021-03-14 23:59 UTC, KarlokCheung commented on src/components/ModalPage/ModalPage.jsx
> +const Overlay = styled.div`
是的，那就可以不用再写一遍了

2021-03-15 00:00 UTC, KarlokCheung commented on src/components/ModalPage/ModalPage.jsx
> +      <Header />
我是先全部写再这个里面再分进去component的，但是components里面只有这一个组件也确实有点奇怪

2021-03-15 00:01 UTC, KarlokCheung commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +  <ModalPage title="重置密码" footer="*该链接仅24小时有效">
那我就拿掉footer让后面用这个组件的时候再按需求加啦

2021-03-15 00:02 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +  <ModalPage title="重置密码" footer="*该链接仅24小时有效">
ModalPage 本身也把footer 去掉吧

2021-03-15 00:03 UTC, KarlokCheung commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +  <ModalPage title="重置密码" footer="*该链接仅24小时有效">
嗯嗯好的

2021-03-16 00:45 UTC, KieraDOG requested changes

2021-03-16 00:45 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +      <FormItem layout="inline" label="新密码">
![image](https://user-images.githubusercontent.com/6457082/111239146-ad6a6680-864c-11eb-8cce-f8d2b89a362e.png)
这一行字漏写了

2021-03-16 00:45 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +      <FormItem layout="inline" label="再次输入">
```suggestion
      <FormItem layout="inline" label="密码">
        <Input />
      </FormItem>
      <FormItem layout="inline" label="确认密码">
```

和成为团长页面保持一致

2021-03-16 00:45 UTC, KieraDOG commented on src/components/ModalPage/ModalPage.jsx
> +import Logo from '../../app/Header/components/Logo';
Logo 有复用性，抽到 app 顶层

2021-03-16 00:47 UTC, KieraDOG commented on src/components/ModalPage/ModalPage.jsx
> +  <Overlay bg="#e0e0e0">
```suggestion
  <Overlay bg="grey">
```

这个 grey 会调用 theme.colors.grey `#f0f0f0`

2021-03-16 01:40 UTC, KieraDOG requested changes

2021-03-16 01:40 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +    </Container>
```suggestion
    <Box py="lg">
      <FormItem layout="inline" label="密码">
        <Input />
      </FormItem>
      <FormItem layout="inline" label="确认密码">
        <Input />
      </FormItem>
      <ConfirmButton size="md" variant="primary">确认</ConfirmButton>
    </Box>
```

2021-03-16 01:40 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +    <Subtitle>您正在进行重制密码操作，请输入新密码。</Subtitle>
```suggestion
    <Box pt="md">您正在进行重制密码操作，请输入新密码。</Box>
```

2021-03-16 01:40 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +      <ConfirmButton size="md" variant="primary">确认</ConfirmButton>
```suggestion
      <Box mt="md">
        <Button size="md" variant="primary">确认</Button>
      </Box>
```

2021-03-16 01:51 UTC, KieraDOG approved these changes

2021-03-16 01:56 UTC, merged