Simonyu/ch443/reset success page
melfish-lorem/1tds pull request #94
Opened 2021-03-16 13:15 UTC by SimonYu-Web

update reset password page and add reset success page

2021-03-16 23:02 UTC, KieraDOG requested changes

2021-03-16 23:02 UTC, KieraDOG commented on src/app/ResetPasswordPage/components/ResetSuccessPage.jsx
> +import React from 'react';
我想了一下重置密码成功不需要单独页面，直接在 ResetPasswordPage 上显示 success message 就可以了

2021-03-17 14:31 UTC, SimonYu-Web commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +      {'}'}
这个位置eslint报错 不得不这个样子  需要龙哥给个解决方法...

2021-03-18 23:02 UTC, KieraDOG requested changes

2021-03-18 23:02 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +            201: '重置密码成功',
```suggestion
            201: (
              <>
                重置密码成功，
                <Button variant="naked">点击重新登录</Button>
              </>
            ),
```

2021-03-18 23:02 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +          }[httpRequestStatus] || '请输入新密码'}
重置密码失败呢？token已过期等情况？

2021-03-18 23:02 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +        <MessageBox mt="lg" variant="info">
在没有 httpRequestStatus 的情况不需要显示这个 message box

2021-03-19 04:33 UTC, SimonYu-Web commented
改好了message box部分 并添加了成功修改密码后 登陆功能

还需要完善的：
如遇到重置密码失败或token已过期等情况的解决方式

2021-03-19 04:54 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +  const { token } = router.query;
```suggestion
  const { query}  = useRouter();
  const { token } = query;
```

2021-03-19 04:57 UTC, KieraDOG approved these changes

2021-03-19 04:57 UTC, KieraDOG commented on src/app/ResetPasswordPage/ResetPasswordPage.jsx
> +        setHttpRequestStatus(status);
```suggestion
        });
        
        setHttpRequestStatus(status);
```

2021-03-19 04:57 UTC, merged